apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: randomnumber-ingress
  namespace: default
spec:
  rules:
  - host: randomnumber.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: randomnumber-service
            port:
              number: 8081
