---
apiVersion: v1
kind: Service
metadata:
  name: randomnumber-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector:
    app: randomnumber-app
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000


