services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/home/bazzite/jenkins_home:/var/home/bazzite/jenkins_home:Z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JENKINS_HOME=/var/home/bazzite/jenkins_home

  redis:
    image: docker.io/library/redis:8
    ports:
      - "6379:6379"
    container_name: redis

  kafka:
    image: docker.io/apache/kafka:4.2.0
    ports:
      - "9092:9092"
    container_name: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    volumes:
      - infra_kafka_data:/tmp/kraft-combined-logs

volumes:
  infra_kafka_data:
